services:
  spotify-sync-api:
    build:
      context: ./src/api
      dockerfile: Dockerfile
      target: production
    container_name: spotify-sync-api
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ${MEDIA_PATH}:/app/media
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}
    networks:
          - frontend
          - backend
    develop:
        watch:
          - action: rebuild
            path: ./src/api
            target: /app

  spotify-sync-ui:
    build:
      context: ./src/ui
      dockerfile: Dockerfile
      target: production
      # target: developmen
    container_name: spotify-sync-ui
    # command: npm run dev -- --host 0.0.0.0 --port 80
    ports:
      - "80:80"
    networks:
      - frontend
      - backend
    develop:
      watch:
        - action: sync
          path: ./src/ui
          target: /usr/share/nginx/html


networks:
  frontend:
    external: true
  backend:
    external: true